services:
  db:
    image: postgres:16
    container_name: pichangaya-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pichangaya
    ports:
      - '5432:5432'
    volumes:
      - pichangaya_pg:/var/lib/postgresql/data

volumes:
  pichangaya_pg:
